apiVersion: v1
kind: Namespace
metadata:
  name: postgresql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: postgresql
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: pgvector/pgvector:0.8.1-pg18-trixie
          env:
            - name: POSTGRES_PASSWORD
              value: "mysecurepassword"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql
      volumes:
        - name: postgres-data
          hostPath:
            path: /mnt/data/postgres
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-lb
  namespace: postgresql
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer
